### ISSUE TITLE
Name of enumeration value shown instead of Caption

### ISSUE THREAD

**Issue by melvingrootenboers** [remcos/EnumClass#2]
1. Run Testproject
2. Click 'New'
3. Select status 'New'
4. Enter name 'Test'
5. Click 'Save'

Result
'_New' shown

Expected result
'New' shown

![image](https://cloud.githubusercontent.com/assets/10810429/13917183/8656ec1e-ef5f-11e5-914a-6de96119e735.png)

**Comment by remcos** [comment]
Hi Melvin, sorry for the late response, but the issue is fixed and submitted for approval in the app store!
